<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Feature: Notification System (F5).
 *
 * The FCM (Firebase Cloud Messaging) token is generated by the Flutter
 * app on startup and uploaded to the server so the backend can target
 * specific devices when pushing notifications.
 *
 * One user can have one active device token at a time. When the user
 * logs in on a new device the token is simply overwritten.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->string('fcm_token', 255)->nullable()->after('api_token');
        });
    }

    public function down(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn('fcm_token');
        });
    }
};
